### PR TITLE
Add a CLI flag to set GRPC address

### PR DESCRIPTION
**Pull request by hashworks**
Otherwise it's not possible to run multiple drone instances on one server (without docker).

### CODE REVIEW

**Comment by vtolstov** [comment]
as i know new drone does not have grpc

**Comment by tboerger** [comment]
I don't think this is required anymore, upcoming version will drop grpc replaced by an rest api. Besides that, officially done is only supported via docker installation, and within the docker container nobody needs to change the grpc port.

**Comment by hashworks** [comment]
> upcoming version will drop grpc replaced by an rest api
What is the timetable here?

> officially done is only supported via docker installation, and within the docker container nobody needs to change the grpc port
Hm, trought so. However I then wondered why the HTTP port is changeable.

**Comment by bradrydzewski** [comment]
closing since 1.0 no longer uses grpc

**Pull request closed without merging**
