### PR TITLE
Implement DRONE_RPC_SKIP_VERIFY for drone-agent and drone-controller

### PR DESCRIPTION
**Pull request by mdluo**
## Background

The `DRONE_RPC_SKIP_VERIFY` is described in the https://docker-runner.docs.drone.io/installation/reference/drone-rpc-skip-verify/ for docker runner. But it has not been implemented in the source code.

This env variable can be useful when the drone server is deployed behind the proxy with dynamically generated self-signed certificates. And adding the certs to the trusted roots of the drone-agent (docker runner) is a complicated operation overhead.

### Setup the local testing environment

1. **Clone the repo**

```sh
git clone https://github.com/mdluo/drone
cd drone
```

2. **Generate self-signed certificate (refer to https://letsencrypt.org/docs/certificates-for-localhost/):**

```sh
openssl req -x509 -out tmp/localhost.crt -keyout tmp/localhost.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```

3. **Prepare nginx config (`tmp/nginx.conf`).**

```conf
server {
  listen 443 ssl;
  ssl_certificate /etc/nginx/conf.d/localhost.crt;
  ssl_certificate_key /etc/nginx/conf.d/localhost.key;
  location / {
    proxy_pass http://drone-server;
  }
}
```

3. **Create `docker-compose.yml`**

```yml
version: '3'
services:
  nginx:
    image: nginx
    volumes: 
      - ./tmp:/etc/nginx/conf.d
    ports: 
      - 443:443
  drone-server:
    image: drone/drone
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=<github-client-id>
      - DRONE_GITHUB_CLIENT_SECRET=<github-client-secret>
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=<rpc-secret>
  drone-agent:
    image: golang:1.13.0
    environment:
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TRACE=true
      - DRONE_SERVER_HOST=nginx
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=<rpc-secret>
      - DRONE_RPC_SKIP_VERIFY=false
    working_dir: /var/drone
    command: go run cmd/drone-agent/main.go
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/var/drone
```

4. **Start with `docker-compose up`**

For now the `DRONE_RPC_SKIP_VERIFY` is set to `false`, so I'm getting error messages:

```log
drone-agent_1   | {"level":"debug","msg":"successfully pinged the docker daemon","time":"2019-10-06T04:59:27Z"}
drone-agent_1   | {"arch":"amd64","level":"debug","machine":"13bdcd2bcdde","msg":"runner: polling queue","os":"linux","time":"2019-10-06T04:59:27Z"}
drone-agent_1   | 2019/10/06 04:59:27 [DEBUG] POST https://nginx/rpc/v1/request
drone-agent_1   | {"arch":"amd64","level":"debug","machine":"13bdcd2bcdde","msg":"runner: polling queue","os":"linux","time":"2019-10-06T04:59:27Z"}
drone-agent_1   | 2019/10/06 04:59:27 [DEBUG] POST https://nginx/rpc/v1/request
drone-agent_1   | 2019/10/06 04:59:27 [ERR] POST https://nginx/rpc/v1/request request failed: Post https://nginx/rpc/v1/request: x509: certificate is valid for localhost, not nginx
drone-agent_1   | 2019/10/06 04:59:27 [DEBUG] POST https://nginx/rpc/v1/request: retrying in 1s (30 left)
drone-agent_1   | 2019/10/06 04:59:27 [ERR] POST https://nginx/rpc/v1/request request failed: Post https://nginx/rpc/v1/request: x509: certificate is valid for localhost, not nginx
```

5. **Change the `DRONE_RPC_SKIP_VERIFY` to `true` and restart**

```log
drone-agent_1   | {"level":"debug","msg":"successfully pinged the docker daemon","time":"2019-10-06T05:00:29Z"}
drone-agent_1   | {"arch":"amd64","level":"debug","machine":"4ca57c88486d","msg":"runner: polling queue","os":"linux","time":"2019-10-06T05:00:29Z"}
drone-agent_1   | 2019/10/06 05:00:29 [DEBUG] POST https://nginx/rpc/v1/request
drone-agent_1   | {"arch":"amd64","level":"debug","machine":"4ca57c88486d","msg":"runner: polling queue","os":"linux","time":"2019-10-06T05:00:29Z"}
drone-agent_1   | 2019/10/06 05:00:29 [DEBUG] POST https://nginx/rpc/v1/request
drone-agent_1   | 2019/10/06 05:00:59 [DEBUG] POST https://nginx/rpc/v1/request (status: 524): retrying in 1s (30 left)
nginx_1         | 172.29.0.4 - - [06/Oct/2019:05:00:59 +0000] "POST /rpc/v1/request HTTP/1.1" 524 25 "-" "Go-http-client/1.1" "-"
nginx_1         | 172.29.0.4 - - [06/Oct/2019:05:00:59 +0000] "POST /rpc/v1/request HTTP/1.1" 524 25 "-" "Go-http-client/1.1" "-"
drone-agent_1   | 2019/10/06 05:00:59 [DEBUG] POST https://nginx/rpc/v1/request (status: 524): retrying in 1s (30 left)
nginx_1         | 172.29.0.4 - - [06/Oct/2019:05:01:29 +0000] "POST /rpc/v1/request HTTP/1.1" 499 0 "-" "Go-http-client/1.1" "-"
drone-agent_1   | 2019/10/06 05:01:29 [ERR] POST https://nginx/rpc/v1/request request failed: Post https://nginx/rpc/v1/request: context deadline exceeded
drone-agent_1   | {"arch":"amd64","level":"debug","machine":"4ca57c88486d","msg":"runner: polling queue","os":"linux","time":"2019-10-06T05:01:29Z"}
drone-agent_1   | 2019/10/06 05:01:29 [DEBUG] POST https://nginx/rpc/v1/request
drone-agent_1   | 2019/10/06 05:01:29 [ERR] POST https://nginx/rpc/v1/request request failed: Post https://nginx/rpc/v1/request: context deadline exceeded
drone-agent_1   | {"arch":"amd64","level":"debug","machine":"4ca57c88486d","msg":"runner: polling queue","os":"linux","time":"2019-10-06T05:01:29Z"}
drone-agent_1   | 2019/10/06 05:01:29 [DEBUG] POST https://nginx/rpc/v1/request
```

Now the drone-agent connect to the drone-server successfully.

###  Tested with GitHub pull request pipeline

Use ngrok as GitHub webhook tunnel

```sh
ngrok http https://localhost
```

If the `DRONE_RPC_SKIP_VERIFY` is set to `true`, the pipeline can be finished successfully.

image

If the `DRONE_RPC_SKIP_VERIFY` is set to `false`, the pipeline gets stuck at the first step and can never move forward.

image

Notice the console output of the second build, the drone-agent is not even connected to the drone server, so there should be no output at all. 
Looks like it's syncing from the first build, it might be a bug.

### CODE REVIEW

**Comment by mdluo** [comment]
@tboerger Thanks for the review.

I agree that it's not complicated, maybe I need to adjust my description. On the one hand, it's already described in the documentation but not implemented, on the other hand, it can be helpful for those who want to deploy drone agent within the same private network (which drone server was deployed) but don't have access to get or set self-signed cert of the drone server.

I did another experiment, seems I have to create another docker image on top of `drone/agent` in order to apply the self-signed cert. Which is not as straightforward as just running the original `drone/agent` image with one extra env variable.

`Dockerfile`

```dockerfile
FROM drone/agent
RUN apk add -U --no-cache ca-certificates
COPY ./tmp/localhost.crt /etc/ssl/certs/
RUN update-ca-certificates
```

`docker-compose.yml`

```yml
version: '3'
services:
  nginx:
    image: nginx
    logging: 
      driver: none
    volumes: 
      - ./tmp:/etc/nginx/conf.d
    ports: 
      - 443:443
  drone-server:
    image: drone/drone
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=<github-client-id>
      - DRONE_GITHUB_CLIENT_SECRET=<github-client-secret>
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=<rpc-secret>
  drone-agent:
    build: .
    environment:
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TRACE=true
      - DRONE_SERVER_HOST=nginx
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=<rpc-secret>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by tboerger** [comment]
Back when I used self signed certificates I have simply mounted a ca-certificates.crt file from the host system via volume to the agents, that's working really well.

But from the usability perspective a separate flag is easier. But especially if the scm is running on a self signed certificate it still gets more complicated as the clone step doesn't provide any skip verify flag, beside that it got to be configured for every pipeline.

For that use case it's much better to provide a ca-certificates.crt file that includes the custom root certificate.

**Comment by mdluo** [comment]
Yes, I found the solution, just exporting the root CA and mount it under `/etc/ssl/certs` (no need to replace `ca-certificates.crt`)

**Comment by bradrydzewski** [comment]
I really appreciate the pull request, however, we actually moved the Docker runner (agent) and Kubernetes runner (controller) to their own separate repositories and skip verify is implemented [1][2]. The agent and controller are now deprecated and are being removed.

[1] https://github.com/drone-runners/drone-runner-kube/blob/master/command/daemon/daemon.go#L68
[2] https://github.com/drone-runners/drone-runner-docker/blob/master/command/daemon/daemon.go#L69

**Pull request closed without merging**
