### PR TITLE
Fix drone filter func

### PR DESCRIPTION
**Pull request by appleboy**
As title. cc @bradrydzewski

### CODE REVIEW

**Comment by appleboy** [comment]
@bradrydzewski need you take this PR. I will write the blog post to introduce the drone filter feature. 👍

**Comment by appleboy** [comment]
ping @bradrydzewski

**Comment by appleboy** [comment]
Hi @bradrydzewski can you take look at this? thanks.

**Comment by tboerger** [comment]
Without this the agent filter is broken, right?

**Comment by appleboy** [comment]
@tboerger Yes.

**Comment by gvishnutej** [comment]
@tboerger @appleboy  Any ETA when this PR will be merged? we want to use filter feature on drone agents

**Comment by appleboy** [comment]
@gvishnutej I don't have permission to merge this PR. I can verify this PR resolve the filter issue.

**Comment by bradrydzewski** [comment]
sorry the delay on my end. I think eventually we will use a different (e.g. simpler) mechanism for routing jobs to different agents. So you should expect the filter to eventually be replaced, but that won't happen for a few months.

**Comment by gvishnutej** [comment]
@bradrydzewski Thanks for merging this fix. I see that `drone:latest` docker image has this change. Is there a plan to release a new version of drone with this fix?

**Comment by geekdave** [comment]
@appleboy does this allow running certain jobs on certain agents?  any quick example you could share, or link to a blog post?  Been hoping for this feature!  Thanks for your time on this!

**Comment by appleboy** [comment]
@geekdave see the @bradrydzewski comment https://github.com/drone/drone/pull/2200#issuecomment-328394983

**Pull request merged**
