### PR TITLE
Fix PostgreSQL error on empty repository list

### LINKED ISSUE #1649: Error with Postgresql and Gogs
On trying to use Drone with Gogs and Postgresql, authentication is successful but throws the error pq: syntax error at or near ")" on logging in. This is with both latest and Drone 0.4. No error seen in logs.

Gogs with Sqlite works perfectly fine. So I suspect something to do with the postgres DB driver issue

### PR DESCRIPTION
**Pull request by strk**
Closes #1649

### CODE REVIEW

**Comment by tboerger** [comment]
:-1: this will break mysql and sqlite

**Comment by strk** [comment]
So another idea could be to always append the empty string
as an element: ` IN (%s,'') `

Unless there's a db-specific sql that could be used ...

**Comment by strk** [comment]
Force-pushed a better approach, just skipping run of a query if the list of repos is known to be empty

**Comment by tboerger** [comment]
LGTM

**Comment by bradrydzewski** [comment]
LGTM thanks for taking the time to fix this!

**Pull request merged**
