### PR TITLE
Updated Alpine base version to 3.8.

### PR DESCRIPTION
**Pull request by jpds**

### CODE REVIEW

**Comment by tboerger** [comment]
Is there any specific reason to switch? The current version should be still maintained.

**Comment by jpds** [comment]
Yeah, keeping up to date with software versions is always a good idea! :)

**Comment by mbger** [comment]
Well, [not necessarily](https://twitter.com/lemiorhan/status/935578694541770752).

**Comment by Daviey** [comment]
3.8 has been out since June and shares the current latest tag.  Would seem like a good idea to track the latest upstream release, rather than pin to an ageing version forever?

@mbger The OSX security issue seems pretty irrelevant for this?

**Comment by tboerger** [comment]
I would not pin to an aging version forever, but the currently used version is totally fine supported so far. So imho it's not really required to update it yet.

**Comment by mbger** [comment]
@Daviey My comment not only seems irrelevant, it **is** irrelevant for this issue. Just wanted to make the point that a general statement like _keeping up with software versions is **always** a good idea_ imho is not true.

**Pull request closed without merging**
