### PR TITLE
enable to set user name who builds in .drone.yml

### PR DESCRIPTION
**Pull request by masarakki**
I want to use my own docker image but run builds by non-root user.

### CODE REVIEW

**Comment by masarakki** [comment]
related: https://github.com/drone/images/issues/32

**Comment by tsuchikazu** [comment]
:+1:

**Comment by purehyperbole** [comment]
+1

**Comment by gutenye** [comment]
:+1: I really need this to run my own archlinux image to publish AUR package. And `$ makepkg from ArchLinux` must run as non-root. When will this be merged?

**Comment by shawnzhu** [comment]
see [issue #363(comment)](a quick workaround could be adduser and then su in your build script.)
> a quick workaround could be `adduser` and then `su` in your build script.

**Comment by bradrydzewski** [comment]
merged 0.4 into master. Because 0.4 plugins rely on a shared `/drone` volume across all containers, and the plugins (including git plugin) run as root we need the build container to run as root as well. This is a technical limitation of the 0.4 design.

**Pull request closed without merging**
