### PR TITLE
create new build on restart (issue #2035)

### PR DESCRIPTION
**Pull request by jashandeep-sohi**

### CODE REVIEW

**Comment by jashandeep-sohi** [comment]
@bradrydzewski is there anything else I need to change?

**Comment by bradrydzewski** [comment]
LGTM

I am working on some UI changes that will handle the fact that restart creates a new build number. Once my UI changes are in place we can merge this. Thanks for the PR!

**Comment by jashandeep-sohi** [comment]
@bradrydzewski I haven't been following the changes...where did `client/*` go?

**Comment by vaijab** [comment]
> I haven't been following the changes...where did client/* go?

I believe it's here: https://github.com/drone/drone-go

**Comment by bradrydzewski** [comment]
this was combined and merged in a separate pr, so we can close. thanks!

**Pull request closed without merging**
