### PR TITLE
Use 'which' (if present) to check socat anywhere in path #869.

### PR DESCRIPTION
**Pull request by jvortmann**
When using a base image that is not the provided ones (some custom container), the socat utility
could have been installed on a diferent place than /usr/bin. For instance, yum on CentOS installs
socat on /usr/local/bin.

This commit just rely ou 'which' (when present) to check if socat exists anywhere on the path.
Also, if socat is installed anywhere by /usr/bin before this, the access to services failed
silently.

### CODE REVIEW

**Comment by JeanMertz** [comment]
While in favour of this change, I'd suggest changing `which` to something like `command -v`.

See: http://stackoverflow.com/a/677212/747032

**Comment by jvortmann** [comment]
@JeanMertz makes sense. Already push the changes. Using command is even better because you don't even need to check for which presence, as it is builtin.

**Comment by jvortmann** [comment]
@JeanMertz I've opened a new pull-request, as this one fails the tests because there is more than 1 commit. Check out #932.

**Comment by bradrydzewski** [comment]
> I've opened a new pull-request, as this one fails the tests because there is more than 1 commit. Check out #932.

fyi, has nothing to do with > 1 commit. There is an issue with one of our postgres unit test that occasionally fails due to incorrect ordering. I re-ran the build and it passed

**Comment by jvortmann** [comment]
@bradrydzewski thanks for the heads up :+1: The useful commit is in the new PR anyway :)

**Pull request closed without merging**
