### PR TITLE
Quick fix for build author length on Stash remote

### PR DESCRIPTION
**Pull request by josmo**
Trimming build author length to 40 for default
Removing un-needed comment

### CODE REVIEW

**Comment by josmo** [comment]
@bradrydzewski This is just a quick fix for folks using the stash remote with long author names/emails

**Comment by josmo** [comment]
Actually looking at this a bit more would it make sense for the Author and not have the author be "John Doe <john.doe@test.com>", I'm thinking this would make more sense for plugins that use the DRONE_COMMIT_AUTHOR and DRONE_COMMIT_AUTHOR_EMAIL envs since I'm assuming this is where it comes from.

**Comment by josmo** [comment]
@bradrydzewski I ended up leaving the author as the name and not including the email since it will make down stream plugins more normalized to use and matches other remotes.  I also finally started adding tests :).

**Comment by josmo** [comment]
@appleboy Just wanted to let you know I moved to using the name as the owner since it's more fitting and there's a location for the Author and Author email (since it was one of the changes you had made).  If you look at plugins like git-push it will use the value for the Author for the name and author email for the email address so it makes more sense to keep this consistent :)

**Comment by appleboy** [comment]
@josmo Nice. I got it.

**Pull request merged**
