### PR TITLE
fix code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
#### Description
This PR fixes a few issues that were affecting the code quality.

#### Summary of changes
- Remove unnecessary wrapping of function call
- Remove unnecessary use of slice
- Replace use of HTTP codes with constants

### CODE REVIEW

**Comment by withshubh** [comment]
@bradrydzewski :wave: Please review this PR! :sparkling_heart:

**Comment by withshubh** [comment]
@tboerger please review this PR! :sparkles:

**Comment by marko-gacesa** [comment]
Thank you!

**Comment by withshubh** [comment]
@marko-gacesa Thanks for reviewing and merging the PR!
Take a look at other issues in the codebase here - https://deepsource.io/gh/withshubh/drone

Most of the issues are Autofixable by DeepSource.
Let me know what you think about it.

**Pull request merged**
