### PR TITLE
Update repo.go

### PR DESCRIPTION
**Pull request by u2takey**
typo

### CODE REVIEW

**Comment by tboerger** [comment]
First of all, the commit message doesn't reflect the change. The other thing is, why do you expect this is a typo?

**Comment by metalmatze** [comment]
To me this seems to correct the way it is?! It's a single value and shouldn't be plural?!

**Comment by bradrydzewski** [comment]
This is a breaking change and would impact the drone-ui and a number of existing integrations. I do not believe there is enough benefit to this change to justify breaking things.

**Comment by u2takey** [comment]
in drone-go and  drone/client/client_impl.go  you use  model.Repo 
```
	AllowDeploy bool   `json:"allow_deploys"            meddler:"repo_allow_deploys"`
	AllowTag    bool   `json:"allow_tags"               meddler:"repo_allow_tags"`
```

but in drone/server/repo.go
```
	AllowDeploy *bool  `json:"allow_deploy,omitempty"`
	AllowTag    *bool  `json:"allow_tag,omitempty"`
```

the difference will cause bug : you cannot you cannot change AllowDeploy AllowTag config

**Comment by bradrydzewski** [comment]
in this case the drone-go and CLI repository would need to change, as opposed to the server endpoint

**Comment by u2takey** [comment]
ok, may change drone-go first

**Pull request closed without merging**
