### PR TITLE
slack: implement on_change

### PR DESCRIPTION
**Pull request by etix**
Add on_change to push slack notifications only in case of status change (like the email plugin) but still allowing to enforce on_failure to always notify when it fails but only once when it succeeds after a failure.

### CODE REVIEW

**Comment by kri5** [comment]
:+1:

**Comment by predominant** [comment]
:+1:

**Comment by kri5** [comment]
Anything blocking this PR to be merged?

**Comment by bradrydzewski** [comment]
merging this now, however, please note that the 0.4 branch (next release) moves all plugins to external projects. This change will therefore need to be ported to the 0.4 release

**Pull request merged**
