### PR TITLE
allow explicit config of drone-exec image

### PR DESCRIPTION
**Pull request by tam7t**
I'd like to be able to build and pin my own `drone-exec` image tags for developing and testing new features.

### CODE REVIEW

**Comment by msteinert** [comment]
https://github.com/drone/drone/pull/1378

I would also like this feature!

I think most of the code in `engine/worker.go` isn't used anywhere. It appears that the actual implementation is in `engine/engine.go`.

**Comment by tboerger** [comment]
I would prefer plain environment variables but the implementation of @msteinert seems to be more flexible and is covered by tests... Difficult topic :)

**Comment by tam7t** [comment]
@msteinert ha thanks for pointing out the dead code. I'll leave this PR open for now as a smaller change-set alternative to #1378

**Comment by macb** [comment]
We deployed this branch internally to deploy an internal `drone-exec` branch for testing and it's worked like a charm.

```
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS              PORTS               NAMES
eaf9db6965f6        ruby:2.2   "/bin/sh -e -c 'echo "   15 seconds ago      Up 14 seconds                           fervent_borg
b28e45b2663c        mysql:5.5                                            "/entrypoint.sh mysql"   15 seconds ago      Up 15 seconds                           ecstatic_goldberg
fc0f0e4ca050        gliderlabs/alpine:3.1                                "/bin/sleep 86400"       21 seconds ago      Up 20 seconds                           furious_elion
6fd9f4b051e4        macb/drone-exec:resume                               "/bin/drone-exec --pu"   21 seconds ago      Up 20 seconds                           drone_build_12536_job_12521
8714ba0efffb        e1ecfedcd76b                                         "/bin/sh -c '/bin/bas"   2 minutes ago       Up 2 minutes                            stoic_darwin
```

**Comment by sylus** [comment]
Is it possible to get an up to date P.R. for this ^_^

**Comment by bradrydzewski** [comment]
fixed in 0.5

**Pull request closed without merging**
