### PR TITLE
Removing legacy docs.

### PR DESCRIPTION
**Pull request by gtaylor**
People keep updating these thinking that this is where they reside. Time to clean house!

Left swagger.yml alone, since I wasn't sure if we were using it.

### CODE REVIEW

**Comment by tboerger** [comment]
The go generate part for the docs is still part of the build process.

**Comment by gtaylor** [comment]
This is going to need some additional checking, but the latest commit is my attempt to remove the last remaining pieces. Once we get to the point of being OK with the PR, I can rebase + squash this. For now we'll do this iteratively until I get it right.

**Comment by tboerger** [comment]
Still missing something. go-bindata doesn't get executed anymore.

**Comment by bradrydzewski** [comment]
I removed as part of some 0.5 changes that I backported :)

**Pull request closed without merging**
