### PR TITLE
#1533 first cut to show only active repos initially

### PR DESCRIPTION
**Pull request by jeffastorey**
I mistakenly opened up 2 PRs against my master at the same time causing one of them to be closed automatically. That was https://github.com/drone/drone/pull/1536.

Reopening as a new PR against a new branch. @tboerger, @Bugagazavr and @bradrydzewski - apologies for the inconvenience here.

### CODE REVIEW

**Comment by Bugagazavr** [comment]
LGTM

**Comment by tboerger** [comment]
LGTM

**Comment by jeffastorey** [comment]
Thanks for the review. Is this good to have merged in?

**Comment by tboerger** [comment]
Needs a rebase after @bradrydzewski changed the structure.

**Comment by jeffastorey** [comment]
rebase complete

**Comment by bradrydzewski** [comment]
thanks! sorry for the delay

**Pull request merged**
