### PR TITLE
Adding ability to pull from a private registry for the build image

### LINKED ISSUE #245: Support Private Docker images
This is the error when trying to use a docker image from a private repository. 
Not sure if this is supported by drone. If not, please support it :)
If yes, please include instructions in the wiki/readme about how to set-up authentication against private docker image repositories.

### PR DESCRIPTION
**Pull request by epipho**
Added an extra section to the drone yml file to define auth credentials for the docker repo, the credentials are passed via http header if set.  This allows drone to pull a docker image from a registry that requires authentication. 

I am still a bit unsure on the exact setup, thoughts?

This also fixes #245 

```
image: quay.io/epipho/test-pvt:latest

auth:
  email: $$email
  username: $$user
  password: $$pass

script:
  - env

```

### CODE REVIEW

**Comment by epipho** [comment]
Any update on when we may be able to bring this in?

**Comment by hkjn** [comment]
Hi, any updates here? We really like drone, but we have a private registry holding all our images, so this is a bit of a blocker for us.

**Comment by adamlc** [comment]
We're pretty desperate for this! Would be great if @epipho could update the PR :dancers:

**Comment by MhdAli** [comment]
This feature is really important for users that using private registry and there is alot of them out there, so I'd love to this live.

Thanks

**Comment by bradrydzewski** [comment]
We accepted a rebased version of this PR that was compatible with the 0.4 codebase. This is now documented at http://readme.drone.io/usage/build_test/#images:fb92aa3346185c57f15afda861d465a3

**Pull request closed without merging**
