### PR TITLE
Image optimize

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Lossless recompression.
```
 vendor/github.com/gin-gonic/gin/logo.jpg            | Bin 12200 -> 11168 bytes
 static/images/dummy.png                             | Bin 11083 -> 5376 bytes
 static/images/favicon.png                           | Bin 557 -> 366 bytes
 vendor/github.com/franela/goblin/goblin_output.png  | Bin 18985 -> 13578 bytes
 vendor/gopkg.in/go-playground/validator.v8/logo.png | Bin 13443 -> 10878 bytes
```

### CODE REVIEW

**Comment by tboerger** [comment]
Drop the optimizations of the vendor files than I'm fine with it, so long it's :-1: for me.

**Comment by PeterDaveHello** [comment]
@tboerger may I know the reason why to drop the optimization on vendor files?

**Comment by tboerger** [comment]
@PeterDaveHello because we don't touch any vendored file? Beside that those files are anyway not part of the built binary at the end. If you want to optimize them do it upstream in the correct repos.

**Comment by PeterDaveHello** [comment]
Okay I've removed them, thanks.

**Comment by tboerger** [comment]
LGTM

**Comment by bradrydzewski** [comment]
LGTM

**Pull request merged**
