### PR TITLE
Gitlab pull requests support

### PR DESCRIPTION
**Pull request by Bugagazavr**
Supported:
- Public fork ( source ) -> Any target ( target )
- Target ( source ) -> Target ( target )

Not supported:
- Any private forks ( source )

### CODE REVIEW

**Comment by shawnzhu** [comment]
| column name            | [github pull request](https://developer.github.com/v3/activity/events/types/#pullrequestevent) | [gitlab merge request](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md#merge-request-events) | [bitbucket pull request](https://confluence.atlassian.com/display/BITBUCKET/pullrequests+Resource#pullrequestsResource-GETaspecificpullrequest)                                                                                                                                                                      |
|------------------------|------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `commit_source_remote` | `pull_request.head.repo.clone_url`                                                             | `object_attributes.source.http_url` or `object_attributes.source.ssh_url`                                                   | it only provides source repo meta info like repo full name, API link, but no source url.  By taking a look at [PR 597(comment)](https://github.com/drone/drone/issues/597#issuecomment-59818032), the source remote url of bitbucket may be generated from `source.repository.full_name` before saving into database |
| `commit_source_branch` | Not found, nor needed                                                                          | `object_attributes.source_branch`                                                                                           | `source.branch.name`                                                                                                                                                                                                                                                                                                 |
|                        |                                                                                                |                                                                                                                             |                                                                                                                                                                                                                                                                                                                      |

Another possible additional data would be title of pull request which is presented in payloads of all remote APIs.

**Comment by Bugagazavr** [comment]
Atlassian Stash allow fetch pull requests from `refs/pull-request/:id/head`

**Comment by bradrydzewski** [comment]
working on getting a final review for #871 which would delegate cloning a repo (including pull requests) to the remote plugins. I think this will allow us to do all sorts of cool stuff

**Comment by bradrydzewski** [comment]
closing since the 0.4 gitlab PR was merged :)

**Pull request closed without merging**
