### PR TITLE
add avatar url for gitlab

### PR DESCRIPTION
**Pull request by letusfly85**
we also want to see avatar when using gitlab.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@letusfly85 thanks! can you verify that we

**Comment by bradrydzewski** [comment]
@letusfly85 quick question about this line:

```diff
+user.Avatar = r.URL + "/" + login.AvatarUrl
```

Are you sure we need to concatenate `r.URL` and `login.AvatarUrl`? I took a look at the GitLab API [documentation](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/users.md) and it appears that `AvatarUrl` was the fully qualified URL:

```
[
  {
    "id": 1,
    "username": "john_smith",
    "name": "John Smith",
    "state": "active",
    "avatar_url": "http://localhost:3000/uploads/user/avatar/1/cd8.jpeg",
  }
]
```

**Comment by letusfly85** [comment]
@bradrydzewski 

I got relative path from gitlab api, I'll ask to gitlab team.

Thank you :smile:

**Comment by bradrydzewski** [comment]
great thanks :)

**Comment by Bugagazavr** [comment]
sample

**Comment by Bugagazavr** [comment]
i think relative and non-relative url specified in config

**Comment by bradrydzewski** [comment]
@Bugagazavr thanks for the tip!

Maybe it makes sense to see if `strings.HasPrefix(login.AvatarUrl, "http")` and if `true` we use the value as-is, and if `false` we construct the url as currently implemented in this pull request?

**Comment by letusfly85** [comment]
@bradrydzewski @Bugagazavr 

Thank you! I'll try to fix it.

**Comment by letusfly85** [comment]
@bradrydzewski @Bugagazavr 

I also think that prefix check is good idea.
however, if some events happens to gitlab by relative path, I think we have to consider about it.. :sweat_drops:

**Comment by bradrydzewski** [comment]
@letusfly85 when a user authenticates it should update the URL. This means that if the avatar URL changes Drone should update the next time the user authenticates.

I also think we can also provide a database update statement (as a gist) to bulk update avatar URLs if there is a change to the gitlab URL format, hostname, etc. This probably happens pretty infrequently, so a manual work-around like this is probably good enough for now :)

**Comment by letusfly85** [comment]
@bradrydzewski 

Thank you for replying.
 
It seems infrequently, and if users can upload manually, there is no problem.

So, I think that this PR will be for first authenticates and logged in.

**Comment by bradrydzewski** [comment]
awesome, thanks!

**Comment by letusfly85** [comment]
Thank you!

**Pull request merged**
