### PR TITLE
config scheduler's host aliases via ENV

### PR DESCRIPTION
**Pull request by bgdsh**
Hi,
this PR is for demo the feature I want in https://discourse.drone.io/t/if-its-possible-to-add-hostaliases-on-the-job-pod/5042 
if it is not qualified to merge, please help to implement it yourself or give me some advice, then I can do the relevant changes.

### CODE REVIEW

**Comment by bgdsh** [comment]
This feature is not only useful for me, it is also useful for the ones who are using github enterprise version.

**Comment by rocketbitz** [comment]
This is also extremely useful for me. Anything holding up this getting merged in besides the `go.sum` conflict? Willing to contribute if needed.

**Comment by bradrydzewski** [comment]
the first, experimental iteration of the kubernetes runner was deprecated back in april. The second experimental iteration now lives here:
https://github.com/drone-runners/drone-runner-kube

also the kubernetes runner was re-architected and it is likely this change is no longer required, since the new implementation no longer uses jobs.

**Comment by rocketbitz** [comment]
Thanks for the clarification @bradrydzewski. Does that mean I can change `DRONE_KUBERNETES_IMAGE=drone/drone-runner-kube:latest` if I want to run the new one, or are there other steps? Thanks in advance.

**Comment by bradrydzewski** [comment]
it is a completely separate installation and has its own dedicated yaml syntax
https://kube-runner.docs.drone.io

**Pull request closed without merging**
