### PR TITLE
fix missing commit sha and wrong tag link for Gitea.

### PR DESCRIPTION
**Pull request by appleboy**
As title

cc @lunny @tboerger @lafriks

### CODE REVIEW

**Comment by tboerger** [comment]
Seriously? Again some fuck up of the gitea api?

**Comment by appleboy** [comment]
@tboerger Maybe you can see the following PR first.

https://github.com/go-gitea/gitea/pull/2836
https://github.com/go-gitea/gitea/pull/2841
https://github.com/go-gitea/gitea/pull/2849

**Comment by lunny** [comment]
not api but commit URL shouldn't gitea should return the URL via the API

**Comment by appleboy** [comment]
@bradrydzewski Can you have time to review this PR?

**Pull request merged**
