### PR TITLE
Fix Marathon deployments

### PR DESCRIPTION
**Pull request by kpacha**
use PUT method instead POST so it creates a new app (if it doesn't already exist) or upgrades it

### CODE REVIEW

**Comment by kpacha** [comment]
@bradrydzewski, the build failed because a timeout during the dependency installation... please, ignore the fail or relaunch the build process

**Comment by taik0** [comment]
+1 
Without this patch the marathon plugin cannot be used.

**Comment by bradrydzewski** [comment]
thanks! just re-ran but it looks like it just might need to be go-formatted in order to pass the build

**Comment by kpacha** [comment]
Fixed!

**Comment by kpacha** [comment]
There is a bug in the order of the parameters...

**Pull request merged**
