### PR TITLE
Proposal: Add building doc and Makefile

### PR DESCRIPTION
**Pull request by flaccid**
The `.drone.sh` requires the closed source enterprise repo and is intended for CI.

Basic documentation on building Drone CI is missing. Can we add in some doc and also make it easier to build by supplying a `Makefile`?

From here, it would be good to also look at dependency management. Currently I've kept it simple by installing the deps manually.

### CODE REVIEW

**Comment by appleboy** [comment]
See https://github.com/drone/drone/pull/2040

**Comment by flaccid** [comment]
Thanks for the link. Certainly a historic `Makefile` there. The new one focuses on being a shortcut/helper to standard commands.

**Comment by tboerger** [comment]
:-1: we have went away from makefile. And for the docs, we got a repo where this can get documented

**Comment by flaccid** [comment]
@tboerger usability is important. I see two docs repositories 👎 .
https://github.com/drone/docs
https://github.com/drone/docs.drone.io

Docs sites:
- http://docs.drone.io/
- http://readme.drone.io/
- http://plugins.drone.io/

Mileage varies, but steps for building is missing from either. Are the docs to be consolidated?

**Comment by tboerger** [comment]
As you can see on the commits it's the docs repo. docs.drone.io is the documentation for current version, readme.drone.io will be dropped, it have been the documentation for older drone versions.

**Comment by donny-dont** [comment]
I don't know that the docs site should have info on how to build drone. The official way is to use the docker images not to build with source. Building from source should be present but in the repo itself in my opinion.

**Comment by bradrydzewski** [comment]
I think I am partial to adding something to docs.drone.io. I have been using docker's tutorials for building docker from source, which were quite helpful. They were a bit more verbose and included more examples than something you would find in a README

In the short term perhaps we add a BUILDFILE to the repository that describes the current build process for people that want to compile drone locally.

```
#
# install dependencies
#

go get -u github.com/drone/drone-ui/dist
go get -u golang.org/x/net/context
go get -u golang.org/x/net/context/ctxhttp
go get -u github.com/golang/protobuf/proto
go get -u github.com/golang/protobuf/protoc-gen-go

#
# install binaries to $GOPATH/bin
#

go install github.com/drone/drone/cmd/drone-agent
go install github.com/drone/drone/cmd/drone-server
```

**Comment by bradrydzewski** [comment]
drone repositories now using BUILDING files

**Pull request closed without merging**
