### PR TITLE
Add docker build command in Makefile.

### PR DESCRIPTION
**Pull request by appleboy**
Add docker build command in Makefile so developer can build docker images as the following command.

```bash
$ make all docker
```

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Comment by bradrydzewski** [comment]
`make all docker` won't work on osx or windows machines because the binary will be compiled for the host machine architecture

**Comment by bradrydzewski** [comment]
it is currently not possible to compile drone on osx or windows for use in a linux container, because it uses CGO to include SQLite. While I appreciate the pull request, my concern is that it will result in developer confusion when they run `make all docker` and it creates an OSX binary file that gets added to the Docker image, which will fail to start

**Comment by appleboy** [comment]
@bradrydzewski Yes.

I want debug on osx. I need the following steps:

* make all
* docker build --rm -t drone/drone .
* docker-compose up

**Comment by bradrydzewski** [comment]
this won't work because `make all` runs `make build_static` which compiles the binary using CGO and results in a binary that only runs on OSX architecture. Adding this binary to the image will cause the image to fail to start.

note that you can run Drone perfectly fine on OSX. It does not require a linux runtime, just a valid Docker daemon url

**Comment by tboerger** [comment]
We should add a shell and bat script that builds the binary within a docker container and than builds the docker container afterwards that can be used

**Comment by tboerger** [comment]
With that we can even get rid of the makefile like we did for plugins

**Comment by bradrydzewski** [comment]
when I develop drone locally I use `go install && drone server`

**Comment by appleboy** [comment]
@tboerger 👍 

Because I run drone on linux machine and debug using https://github.com/drone-demos/drone-on-docker-compose 

When I modified the drone code base, I need run three command as below.

 ```
make all
docker build --rm -t drone/drone .
docker-compose up
```

So I think we can add `docker build command` in Makefile for docker user.

**Comment by tboerger** [comment]
Different users, different commands I'm using make builds static && ./release/drone server

**Comment by appleboy** [comment]
@tboerger I know the `./release/drone server` command. I just want to run docker command in Makefile.

**Comment by tboerger** [comment]
`make all` is btw a waste of compile time because it builds ALL binaries instead of the one you need for development or testing.

**Comment by bradrydzewski** [comment]
@appleboy in this case the command is not cross platform, and would likely result in osx developers trying to use it and logging bugs when it doesn't work. You should definitely feel free to create local shell scripts that help you develop more efficiently, but in some cases like this we may choose not to merge.

**Comment by appleboy** [comment]
@tboerger I know `make build_static`.

I just want to simplify the steps as below on Linux maction:

```bash
make build_static
docker build --rm -t drone/drone .
docker-compose up
```

to

```bash
make build_static docker
docker-compose up
```

For docker user.

**Comment by tboerger** [comment]
I know what you mean. But as I said above, I think building `.sh` and `.bat` files should be better because they are usable on all supported platforms.

**Comment by appleboy** [comment]
@bradrydzewski @tboerger 

OK. Thanks for response quickly. 👍

**Pull request closed without merging**
