### PR TITLE
Clean up status codes.

### PR DESCRIPTION
**Pull request by Alireza-Ta**
Hey
Just change all http status codes to numerical format in ```server``` directory.

### CODE REVIEW

**Comment by xxxtonixxx** [comment]
why??

**Comment by metalmatze** [comment]
I think this is quite the opposite of what you want to do in Go. The constants are way more descriptive and reference the same numbers you've just replaced them with.

**Comment by Alireza-Ta** [comment]
Well, i'm new to go!
I thought if they be in one format would be fine, however you can ignore it if it's a bad practice!

**Comment by metalmatze** [comment]
@Alireza-Ta Thanks for taking the time to contribute nevertheless! I hope you learned something, keep the PRs coming. 👍

**Comment by metalmatze** [comment]
Oh wait. You actually want to use the constants. I'm not really sure how important that is to @bradrydzewski. 🤔

**Comment by tboerger** [comment]
No, I had also been confused. Look at his first commit: https://github.com/drone/drone/pull/2479/commits/8183907c070301440ef8587c92cb7ba4ecb3dc8b

**Comment by Alireza-Ta** [comment]
@metalmatze You said using consts is better than just plain numbers because of that I changed it!

**Pull request closed without merging**
