### PR TITLE
Fix log output

### PR DESCRIPTION
**Pull request by vespakoen**
This also fixes the log output when looking at an old build.

### CODE REVIEW

**Comment by vespakoen** [comment]
related: https://github.com/drone/drone/pull/1680

This pull adds some other fixes that the related pull doesn't have.

**Comment by tboerger** [comment]
Can we merge this to get the log output of beta.drone.io fixed? :)

**Comment by ZombieHippie** [comment]
I'm using this on my server https://drone.dryclean.io/ZombieHippie/angular-2-webpack-starter/3

Logging still isn't perfect but at least it shows up.

**Comment by bradrydzewski** [comment]
we have a completely new UI and won't merge this. I've kept it open so that individuals running 0.5 can patch their local versions while waiting for the new UI

**Comment by bradrydzewski** [comment]
closing now that we've officially switched to drone-ui repository

**Pull request closed without merging**
