### PR TITLE
remove missing target in Makefile.

### PR DESCRIPTION
**Pull request by appleboy**

### CODE REVIEW

**Comment by tboerger** [comment]
When you already touch it, there are other phony tasks.

**Comment by appleboy** [comment]
@tboerger I don't see any target about `vendor`、 `docs` or `release`.

**Comment by tboerger** [comment]
I know, but there are other targets that should be added to phony.

**Comment by bradrydzewski** [comment]
@tboerger I think this is good to merge, no?

**Comment by tboerger** [comment]
@bradrydzewski sure, it doesn't break anything. It does a minor cleanup but we can finish it in another PR.

**Comment by appleboy** [comment]
Hi @tboerger @bradrydzewski 

I merge this PR into #1750 ?

**Comment by tboerger** [comment]
Please keep it like it is

**Pull request merged**
