### PR TITLE
chore: add grpc health check.

### PR DESCRIPTION
**Pull request by appleboy**
fix https://github.com/drone/drone/issues/2246

cc @jmccann @tboerger @bradrydzewski

### CODE REVIEW

**Comment by jmccann** [comment]
@appleboy Thanks for tackling this!!

Not sure I can offer a LGTM as I don't have confidence in my go-fu for this one but I'd be willing to test this in my dev environment if it gets merged (I use EE features in dev so can't compile/test myself in existing dev env ...)  😄 

The only comment I have otherwise is if we should have this enabled by default or have it disabled by default for now until we have more confidence in the check.

Thanks again!!!

**Comment by appleboy** [comment]
@jmccann I try this solution on Kubernetes. It still not working for me. Maybe you can help to try on Kubernetes or Docker swarm but it is working for binary install or docker-compose.

**Comment by appleboy** [comment]
@tboerger already rebase.

**Comment by bradrydzewski** [comment]
> I try this solution on Kubernetes. It still not working for me

If I understand correctly, this patch doesn't solve the issue? If so, I think we should wait and merge a working solution.

**Comment by appleboy** [comment]
@bradrydzewski Yes. maybe we should wait for another solution.

**Comment by Rush** [comment]
@appleboy any news?

**Comment by bweston92** [comment]
Any update, seems to happen quite alot and requires setting jobs from "pending" to "failed" in the db to clear them as they don't start after restarting everything.

**Comment by bradrydzewski** [comment]
> Any update, seems to happen quite alot and requires setting jobs from "pending" to "failed" in the db to clear them as they don't start after restarting everything.

I am not personally putting any effort into this at the moment. This only seems to happen to individuals using a reverse proxy or load balancer, which is not currently a supported configuration since there are known grpc issues. You can try to use the new keep alive settings with the agent, but ymmv

**Comment by appleboy** [comment]
@bweston92 You can see discussion here. https://discourse.drone.io/t/0-8-1-agent-loses-connection-overnight/864

**Comment by tonglil** [comment]
Now that #2294 is in, what's the next steps for this?

**Comment by bradrydzewski** [comment]
@tonglil this pull request should probably be closed in favor of an alternate, working solution.

**Pull request closed without merging**
