### PR TITLE
always update docker image

### PR DESCRIPTION
**Pull request by masarakki**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
What about making this behavior a bit more explicit. For example, if I specify `:latest` in the image name it will always check the registry for an updated version? Instead of checking every single time?

```diff
-	if _, err := b.dockerClient.Images.Inspect(b.Build.Image); err == docker.ErrNotFound {
+	if _, err := b.dockerClient.Images.Inspect(b.Build.Image); err == docker.ErrNotFound || strings.HasSuffix(b.Build.Image, ":latest") {
		// download the image if it doesn't exist
		if err := b.dockerClient.Images.Pull(b.Build.Image); err != nil {
			return fmt.Errorf("Error: Unable to pull image %s. %s", b.Build.Image, err)
		}
	}
```

**Comment by jvliwanag** [comment]
Hm, or might it be better as an explicit option in the yaml? And by default, this is `false`.

Setting this to be true when the tag is set as `latest` is odd.

**Comment by bradrydzewski** [comment]
@jvliwanag `latest` is the official Docker tag for the latest revision:
https://github.com/docker/docker/blob/8f3ecf8779fd450d63049f53f65899d41cf759d6/graph/tags.go#L21

I think it is pretty appropriate

**Comment by jvliwanag** [comment]
Yes, but in the same manner as `docker run myimage:latest` doesn't pull an image every time I run it, I'm thinking nor should drone do the same per build.

I can imagine pulling the image of a certain tag to be useful in some cases. Tags which are not necessarily `latest`. (e.g. if i have a `dev` tag). So having it as an explicit yaml option would be my vote, vs being implicitly defined by using the `:latest` tag. Moreover, it's confusing that using the bare image name without any tags specified would pull the `latest` on first use but not pull it every build.

**Comment by bradrydzewski** [comment]
The services section of the yaml file is a string array of image names. Using `latest` would allow us to pull individual service images without having to change the yaml file. But maybe service images aren't as big of a deal.

Either way I vote for the simplest solution, whatever that may be, since it will get deprecated in a few weeks when #902 is introduced.

**Comment by masarakki** [comment]
I think in drone, we use tags like `go:1.2` with meanings that 'this image has go version 1.2',
so I thinks `go:1.2` is NOT immutable.   
for example, current `ruby:2.0.0` has `ruby-2.0.0-p195`, and upgrade it to `ruby-2.0.0-p598`,
I expected `ruby:2.0.0` will be updated.
Is it wrong way of thinking?

**Comment by bradrydzewski** [comment]
The official language stacks are immutable. They share the same underlying base image to save space, but do not build on eachother. Check out the official [go 1.3](https://github.com/docker-library/golang/blob/1a422afd7db928a821e97906ed27ed606e2f072a/1.3/Dockerfile) and [go 1.4](https://github.com/docker-library/golang/blob/1a422afd7db928a821e97906ed27ed606e2f072a/1.4/Dockerfile) dockerfiles for example.

We have already solved this problem in the upcoming 0.4 release as part of the yaml file re-design, and in response to #697. Anything we do here will be a temporary fix until 0.4 is available.

**Comment by masarakki** [comment]
change to update only when `:latest` tag.

**Comment by bradrydzewski** [comment]
thanks for being open to the temp fix. The permanent fix will master in a couple weeks :)

**Pull request merged**
