### PR TITLE
Refine .drone.yml pipeline design

### PR DESCRIPTION
**Pull request by guessi**
Fixed the following problems:

- Golang version in `.drone.jsonnet` was pointed to [1.11](https://github.com/drone/drone/blob/v1.7.0/.drone.jsonnet#L4), but [1.13.0](https://github.com/drone/drone/blob/v1.7.0/.drone.yml#L12) in `.drone.yml`

- Multiple fileds not aligned in `.drone.yml`, `.drone.jsonnet`.

**Updated**

- May 10, 2020 - remove section of `drone-agent` and `drone-controller`
- Sep 24, 2020 - rebase v1.9.1
- Sep 24, 2020 - `.drone.yml` and `.drone.jsonnet` was removed, ref: https://github.com/drone/drone/commit/0e4af8d35b9fd3ecd1302a9a96d3efcbe64414dc

### CODE REVIEW

**Comment by guessi** [comment]
I'm aware there is another PR for bumping golang version #2936, but this PR is aim to keep `.drone.yml` and `.drone.jsonnet` aligned, but not version bumping. So I just bump the golang version to `1.13.0` to keep aligned with [.drone.yml (v1.7.0)](https://github.com/drone/drone/blob/v1.7.0/.drone.yml#L12).

**Comment by tboerger** [comment]
Controller and agent won't receive any updates, they are deprecated in favor of the runners built on the runners github organization.

**Comment by guessi** [comment]
@tboerger Oops, I didn't aware there's another GitHub organization [drone-runners](https://github.com/drone-runners) exist.

I've update the PR, removed the logic for `agent` and `controller`, with some fixes, please review the PR again, thanks.

**Comment by guessi** [comment]
Questions,

- Should I update `.drone.star` as well? or just leave it untouched?
- Should I remove the logic for `agent` and `controller` from the file `scripts/build.{sh,ps1}`?

**Comment by guessi** [comment]
close, since most update was override by 4a1c639 and removed in 0e4af8d

**Pull request closed without merging**
