### PR TITLE
Update Sirupsen/logrus dependency

### PR DESCRIPTION
**Pull request by jen20**
This commit updates the github.com/Sirupsen/logrus dependency to a version which will correctly compile on Solaris and Illumos derived operating systems such as SmartOS.

The new revision is [4b6ea731](https://github.com/Sirupsen/logrus/commit/4b6ea7319e214d98c938f12692336f7ca9348d6b).

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by jen20** [comment]
Is there any guidance on when we might expect to see this merged?

**Comment by bradrydzewski** [comment]
included and merged as part of #1569

**Comment by jen20** [comment]
Thanks @bradrydzewski!

**Pull request closed without merging**
