### PR TITLE
fix missing semicolon in Postgres script's files

### PR DESCRIPTION
**Pull request by Valeran86**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
The semi-colons are not necessary because we generate .go code from the .sql files. Check out: https://github.com/drone/drone/blob/master/store/datastore/ddl/postgres/ddl_gen.go

**Comment by tboerger** [comment]
But it's just consistent to add them as you have written them on most migration sources :)

**Comment by bradrydzewski** [comment]
once the CLI is signed we can merge

**Comment by tboerger** [comment]
Seems to be signed

**Pull request merged**
