### PR TITLE
Replace configuraiton by configuration in router/middleware/remote.go

### PR DESCRIPTION
**Pull request by bbenoist**
:art:

### CODE REVIEW

**Comment by bradrydzewski** [comment]
should I assume that the frowny face means you won't be signing the CLI? If so let me know and I will close this pull request. Like it or not, this is the policy

**Comment by bbenoist** [comment]
@bradrydzewski Nope, I might sign it but not today (22:30 in France) as I have to ask for an explicit agreement to my superiors before.

I used the *confused* reaction because, although I understand and respect your policy, this requirement looked too strong regarding of how trivial was this PR.

However, considering:
* how easy it would be for you to make the change by yourself
* how long it would take for me to get an explicit agreement
* the fact that there actually is a typo issue

could you please [edit the file by yourself](https://github.com/drone/drone/edit/master/router/middleware/remote.go) and close this PR instead?

**Comment by bradrydzewski** [comment]
the request to sign a CLA is automated for every new pull request. We do however support the obvious fix rule which is defined as the following:

> HOWEVER, very small contributions such as fixing spelling errors, where the content is small enough to not be considered intellectual property, can be submitted by a contributor as a patch, without a CLA. If you submit an obvious fix without first signing a contributor license agreement, then you are agreeing that your submission is not independently copyrightable. The purpose of this exception is to lower the barrier for new contributors to make contributions while retaining the integrity of the project and our community.

We can accept this change under the obvious fix rule if you include the words `obvious fix` in the commit message.

```
------------------------------------------------------------------------
commit 370adb3f82d55d912b0cf9c1d1e99b132a8ed3b5
Date:   Wed Sep 18 11:44:40 2013 -0700

  Fix typo in config file docs.

  Obvious fix.
------------------------------------------------------------------------
```

I hope that helps. If this is too much trouble for a simple spelling fix let me know, and I can close the pull request and make the change myself. Thanks!

**Comment by bbenoist** [comment]
> We can accept this change under the obvious fix rule if you include the words `obvious fix` in the commit message.

:+1: I will make the change by myself. Thank you for pointing out such feature!

**Pull request closed without merging**
