### PR TITLE
Add master build list endpoint for wall

### PR DESCRIPTION
**Pull request by scottferg**
@bradrydzewski this adds a top level build list (similar to what we added to v3) that is necessary for drone-wall to operate.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@scottferg I think you can use the existing `/api/user/feed` endpoint for this

**Comment by scottferg** [comment]
Yup! Totally can. Serves me right for not reading the docs.

**Comment by bradrydzewski** [comment]
actually, it isn't in the docs haha :)

**Comment by bradrydzewski** [comment]
for reference, the reason this wasn't documented was I didn't want to advertise the endpoint until it was benchmarked in case it needed to be removed or tweaked. The benchmark was positive (you can see at https://github.com/drone/drone/issues/1234) so you should be good to rely on this endpoint going forward.

**Comment by scottferg** [comment]
Ha cool. I don't feel like as big of an idiot. This will make getting the wall up to snuff much easier either way.

**Pull request closed without merging**
