### PR TITLE
Use HipChat API ver 2 for notifications

### PR DESCRIPTION
**Pull request by 907th**
This PR includes 2 fixes actually:
* jsonmessage was moved from github.com/docker/docker/utils to [github.com/docker/pkg/jsonmessage](https://github.com/docker/docker/tree/master/pkg/jsonmessage). I've just fixed the dependency.
* HipChat API v1 [is deprecated](https://www.hipchat.com/docs/), but github.com/andybons/hipchat (used by Drone) does not support v2. So I've implemented v2 using native http.PostForm.

### CODE REVIEW

**Comment by 907th** [comment]
@bradrydzewski I think that the build is failing because Drone CI have cached `docker` repo at `/var/cache/drone/src/github.com/docker/docker`.  Am I right? The build should be OK with the latest `docker` sources.

**Comment by bradrydzewski** [comment]
the problem was (and I'm not sure if it is fixed) that I was unable to `go get ./...` docker because some of the underlying files rely on a script being executed to generate some `.go` files, which caused failures.

so at the moment we rely on cloning a fixed Docker version by running `make docker`. By cloning, as opposed to `go get` it prevented Go from trying to compile and thus won't fail due to the missing files that need to be generated.

it was a total hack

maybe we split into two PRs? One that addresses Hipchat and a second that tries to fix the Docker dependency issue? Might simplify things

**Comment by 907th** [comment]
@bradrydzewski Ok, I'll split it tomorrow

**Comment by 907th** [comment]
I have splitted it into #973 and #974

**Pull request closed without merging**
