### PR TITLE
[WIP] Phabricator remote integration

### PR DESCRIPTION
**Pull request by tboerger**
This is currently work in progress. I have started to integrate phabricator as a remote into drone. The authentication already works, but now we need to find ways to add the other missing parts as well.

The client parts are taken from the Gitlab client.

### CODE REVIEW

**Comment by tboerger** [comment]
It still doesn;t really work is much more complicated. As nobody requested that I will close that for now.

**Comment by tlwt** [comment]
is there any suggested way on working with phabricator? I really appreciate the drone as well as phabricator and think a combination of both would be great!

**Comment by tboerger** [comment]
An phabricator remote driver must implement the interface defined at https://github.com/drone/drone/blob/master/remote/remote.go. 

I don't know how open brad is for new remote drivers or if he wants to enable an external service implementation instead of this.

**Comment by tlwt** [comment]
If you mean by external services that you can create some random web hook and drone kicks off - that would be great as well, I suppose.

**Comment by zicklag** [comment]
I would *really* like to be able to integrate Phabricator with Drone somehow.

**Comment by zicklag** [comment]
Cool, I might look into that after 0.9 comes out, then. :slightly_smiling_face:

**Comment by mavimo** [comment]
@bradrydzewski I suppose should be https://github.com/drone/drone-scm

**Comment by bradrydzewski** [comment]
oops, it is https://github.com/drone/go-scm

**Pull request closed without merging**
