### PR TITLE
Run gofmt and add test to prevent regressions

### PR DESCRIPTION
**Pull request by mattbostock**
Run `go fmt ./...` [1] and add a test to the `test` make target that checks if `go fmt` has been run.

[1]: http://blog.golang.org/go-fmt-your-code

### CODE REVIEW

**Comment by mattbostock** [comment]
Looking into the build failure.

**Comment by Bugagazavr** [comment]
because `go fmt -n ./...` returns list of packages with files, even if these files if normal.

**Comment by bradrydzewski** [comment]
I really like the idea. What about something like `gofmt -l ./.. | read`?

**Comment by Bugagazavr** [comment]
@bradrydzewski yes it works
`test -z "$(gofmt -l ./.. | grep "../drone/")" || echo "Need to run 'go fmt ./...'"; exit 1`

**Comment by mattbostock** [comment]
@Bugagazavr Yep, that was the problem.

I've just pushed an amendment, let me know what you think.

**Comment by bradrydzewski** [comment]
awesome, thanks!

**Pull request merged**
