### PR TITLE
publish/docker: login should happen early

### PR DESCRIPTION
**Pull request by vaijab**
This fixes an issue where base image which drone is using to build an
image for publishing comes from a private repo.

### CODE REVIEW

**Comment by vaijab** [comment]
Any update on this please?

**Comment by dangra** [comment]
`docker login` must happen before `docker build` because of `--pull` right?

I guess your base repository (FROM directive) is private and in the same registry that you are publishing built images.

It still won't work if registry for base image is different to registry used to publish the built image but not a common case.

**Comment by vaijab** [comment]
That's right @dangra

**Comment by dangra** [comment]
+1 to merge :)

**Pull request merged**
