### PR TITLE
ability to provide secret to agent and generate token

### PR DESCRIPTION
**Pull request by bradrydzewski**

### CODE REVIEW

**Comment by gtaylor** [comment]
Very nice. This will simplify our demos a bit.

**Comment by fixe** [comment]
Awesome.

**Comment by fixe** [comment]
We should add this to the docs!

**Comment by bradrydzewski** [comment]
yes, I've got an updated version of the 0.5 docs I'll push tomorrow. Trying to finalize the docs for a release!

**Pull request merged**
