### PR TITLE
GitLab: set DRONE_COMMIT_LINK in case of push event

### PR DESCRIPTION
**Pull request by quantonganh**

### CODE REVIEW

**Comment by bclermont** [comment]
Can someone review this and merge this if it make sense?

**Comment by favadi** [comment]
This MR is so useful that I wish I could merge it 1000 times right now.

**Comment by bclermont** [comment]
there is no point to contribute any improvement and bug fixes if they are ignored

@quantonganh you should just close the PR

**Comment by sebschaub** [comment]
That's useful, can you review and merge it?

**Comment by CandySunPlus** [comment]
please merge it

**Comment by baocaixiong** [comment]
🙏please

**Comment by bradrydzewski** [comment]
this should be resolved now, but relevant code was moved to github.com/drone/go-scm

**Pull request closed without merging**
