### PR TITLE
Test real UTF8 in MySQL

### PR DESCRIPTION
**Pull request by MorrisJobke**
- change the tests to utf8mb4

cc @bradrydzewski 

I will send an PR for documentation to make setting up MySQL with utf8mb4 and drone easy.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
```
time="2016-10-21T10:00:51Z" level=error msg="Error 1071: Specified key was too long; max key length is 767 bytes" 
```

This wasn't the case here 😕 

Is this maybe because the signature is not valid and a different drone.yml is used?

**Comment by bradrydzewski** [comment]
@MorrisJobke that is unrelated to the yaml signature. This error message comes from failing unit tests which were impacted by this change

**Comment by MorrisJobke** [comment]
I have no idea why, but this now also happens for me. Good then I can check out what is going on

**Comment by bradrydzewski** [comment]
the issue is that drone uses composite keys for unique index (ie repo_owner and repo_name) which cannot exceed a combined value of 767 bytes. When using utf8mb4 these column sizes need to be reduced to account for the extra bytes required by the encoding.

note this is for mysql only. The sqlite and postgres column sizes do not need to be adjusted

**Comment by MorrisJobke** [comment]
> the issue is that drone uses composite keys for unique index (ie repo_owner and repo_name) which cannot exceed a combined value of 767 bytes. When using utf8mb4 these column sizes need to be reduced to account for the extra bytes required by the encoding.

Yes, I know - I just had no time yet to change this. I will come up with proper documentation and proper test setup here :)

**Pull request closed without merging**
