### PR TITLE
Implement secrets concealer in build logs

### PR DESCRIPTION
**Pull request by vaijab**
Looks like so:

screenshot from 2016-10-16 12-35-01

### CODE REVIEW

**Comment by bradrydzewski** [comment]
LGTM

**Comment by vaijab** [comment]
Docs update PR: https://github.com/drone/docs/pull/188

**Comment by tboerger** [comment]
LGTM

**Comment by bradrydzewski** [comment]
my apologies, this has some conflicts that need to be resolved after I merged the new message broker branch. Once resolved this can be merged right away

**Comment by vaijab** [comment]
No worries. Will sort the conflicts in the morning.

**Comment by donny-dont** [comment]
@vaijab any updates? i just added a coverage token to my repo in beta.drone.io and saw it leak in the logs there...

**Comment by vaijab** [comment]
> any updates?

@donny-dont sorry, give me an hour. Had a hectic day.

**Comment by vaijab** [comment]
@bradrydzewski @donny-dont rebased and merge conflicts resolved.

**Pull request merged**
