### PR TITLE
Unit tests for PostToken API

### PR DESCRIPTION
**Pull request by benschumacher**
Initial table-based unit tests for Token creation.

### CODE REVIEW

**Comment by benschumacher** [comment]
There is an issue with the invariants in this code, and I took a guess at fixing them, but I may have gone the wrong way. Here's the brief description of the changes to `token.go`:

1.  `server.ToSession(c)` uses gin's `MustGet()`, making a `session.Session` required
2. `PostToken()` handles `settings.Session` being unset/insufficient by [returning an error](https://github.com/drone/drone/pull/1020/files#diff-40b24cc3eaef42cbc89055e5aadc3364R21)

I made a big change that allows the `session.Session` to be created if it doesn't exist, but it may have been simpler to just move the `sess := ToSession(c)` to come after the if condition above. I *believe* that would be sufficient to more closely match our invariants for the remainder of the method.

**Comment by benschumacher** [comment]
(I think I was working from the assumption that `session.Session` mapped to a user's cookie-based session, but upon further reflection and review, this assumption appears to be incorrect.)

**Comment by bradrydzewski** [comment]
hey Ben, if I understand the issue correctly, could the unit test instead invoke `SetSession` to add the session to the context?

**Comment by benschumacher** [comment]
It does, but I want trying to cover branches, too.

My read of the functionality was that if you don't set `settings.Setting.Session.Secret` you wouldn't have a valid `session.Session`. Therefore, to exercise different branches, the table that drives the test is flexible enough to allow for this behavior. Does that make sense?

**Comment by bradrydzewski** [comment]
`settings.Setting.Session.Secret` will fallback to the oauth secret for signing tokens

**Comment by bradrydzewski** [comment]
https://github.com/drone/drone/blob/0.4.0/pkg/settings/settings.go#L121

**Comment by benschumacher** [comment]
Alright. I think test and code match expectations based on changes I missed. Cheers!

**Pull request merged**
