### PR TITLE
Go 1.6 support vendor directory by default.

### PR DESCRIPTION
**Pull request by appleboy**
Please see the detail information about Go 1.6 release note: https://blog.golang.org/go1.6

Signed-off-by: Bo-Yi Wu appleboy.tw@gmail.com

### CODE REVIEW

**Comment by appleboy** [comment]
@bradrydzewski Please help review this PR?

**Comment by tboerger** [comment]
LGTM, but brad got to sign the config afterwards

**Comment by appleboy** [comment]
@tboerger Yes. need brad to resign the config.

**Comment by bradrydzewski** [comment]
fixed in master

**Pull request closed without merging**
