### PR TITLE
Disallow to deactivate repo without admin permissions

### PR DESCRIPTION
**Pull request by Bugagazavr**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
this is handled through middleware:
https://github.com/drone/drone/blob/master/router/router.go#L87

right now it uses `session.MustPush` but could be changed to `session.MustAdmin`. Also note the perms are stored in the context, so it is un-necessary to fetch them again.

**Comment by Bugagazavr** [comment]
i try to use `repo.DELETE("", session.MustAdmin(), server.DeleteRepo)`, but when i try to delete drone from my own repo i got 413 ( typo? )

https://github.com/drone/drone/blob/master/router/middleware/session/user.go#L80

And so, user should be repository admin, but not a system admin, this middleware check is user a drone admin

**Comment by bradrydzewski** [comment]
@Bugagazavr `session.MustRepoAdmin` would need to be created. Forgot that `session.MustAdmin` exists and is used for admin roles.

**Comment by Bugagazavr** [comment]
@bradrydzewski done

**Comment by Bugagazavr** [comment]
maybe add MustRepoAdmin to chown?

**Comment by bradrydzewski** [comment]
> add MustRepoAdmin to chown

sure!

**Comment by Bugagazavr** [comment]
done

**Comment by bradrydzewski** [comment]
thanks!

**Pull request merged**
