### PR TITLE
fixes issues running services in detached mode

### PR DESCRIPTION
**Pull request by bradrydzewski**

### CODE REVIEW

**Comment by bradrydzewski** [comment]
this PR enables optionally defining service containers inside the pipeline using detached mode for better control over execution order. This was previously possible, but resulted in a linter error when trying to override entrypoint or command, which this PR fixes.

```
pipeline:
  build:
    image: golang
    commands:
      - go build
  database:
    detach: true
    image: postgres
  ...
```

**Comment by vaijab** [comment]
Sounds sensible. I still wish there was a way to run dind in privileged mode without trusting a repo. ;/

**Comment by bradrydzewski** [comment]
@vaijab the issue is someone could `docker run` a container that mounts a volume to the parent (dind) container, and use that to escalate privilege to the host machine. Privileged containers have access to all devices on the host machine, and the ability to mount.

the good news is that running dind has definitely gotten easier over time, and I'm confident that one day we will be able to eventually run containers inside containers without escalated privileges. I believe it is already possible with LXC. So while we have these limitations today, hopefully they will be lifted in the future :)

**Comment by vaijab** [comment]
> Privileged containers have access to all devices on the host machine, and the ability to mount.

Yes, for this to work, you would have to do the mounting, etc in dind, not in containers running on top of dind.

Technically it is still possible, because privileged containers have access to the underlying kernel, but if the repo is not trusted explicitly, then only the dind has access to the kernel because we're trusting dind service implicitly, which is why I think this is a much better way of doing than trusting every single repo and letting every single container to access the underlying kernel.

**Comment by bradrydzewski** [comment]
@vaijab yes, this would be another good use case for pluggable yaml transformations. I've added the use case to https://github.com/drone/drone/issues/1863

**Pull request merged**
