### PR TITLE
Drone Job Resource Limits / Requests

### PR DESCRIPTION
**Pull request by gambol99**
- adding environment variables allowing use to set the limits and requests on the batch job
- namely as it was inheriting out default limits and getting oom at 400Mi

@note, i'm not sure if `JOB` is the right description for this? ..

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
I can see this being super useful.  👍  

Job feels appropriate IMO

**Comment by bradrydzewski** [comment]
we do something similar for Nomad [1] and we use `RequestMemory` and `RequestCPU`. I recommend using the same variables for Kubernetes for consistency reasons.

[1] https://github.com/drone/drone/blob/master/scheduler/nomad/nomad.go#L89:L94

**Comment by bradrydzewski** [comment]
this capability is available in the new kubernetes runner home, which can be found at https://github.com/drone-runners/drone-runner-kube

**Comment by geekgonecrazy** [comment]
Nice I like the organization into runners 👍 looks like i'll be switching my drone install before long :)

**Pull request closed without merging**
