### PR TITLE
Log truncation

### PR DESCRIPTION
**Pull request by tcely**
Related to #1563 and #1665

### CODE REVIEW

**Comment by tcely** [comment]
With these two changes I'm able to get about 25k lines of logs. (I don't have a build with more output currently.)

The log streaming is nice and fast and shows everything I'm used to. Once you go over the limit though the loop that's dropping lines from the beginning is fairly slow and delays log uploads by a fair amount. I'd like suggestions to make this faster / more efficient if anyone has them.

The next change that will help with supporting very large build logs is compressing the encoded json with something like deflate and sending the proper headers to have the browser inflate it for us.

**Comment by xordspar0** [comment]
Both of the issues you referenced have been closed for quite a while. Is there any other discussion (issues, forum threads) that would provide some background on this?

**Comment by tcely** [comment]
> Both of the issues you referenced have been closed for quite a while. Is there any other discussion (issues, forum threads) that would provide some background on this?

@xordspar0 The issue management around this problem has been quite poor.

The agents limited how much of the build output is sent to the server and drops all output once that limit is reached. This is a huge problem for anyone who has a failing build, as you can't see the cause of the failure and must rebuild manually.

The guessing around DB limits and server / browser limits was not a solution.

**Comment by tboerger** [comment]
Such a huge build output seems to be an exception, otherwise more people would complain about it.

There had been browser crashs without a build log limitation, that's not just a blind guess, this has been tested with different browsers.

As you can see on other issues and pull requests there is generally a slow response time across the last months because brad is focused on the 0.9 release, this is a release with a huge delay already so it's a must to strictly focus on it.

Besides that, 0.9 will drop grpc and replace it with plain http calls, if it will be chunked or something like that to get around some limitations we will see soon.

**Comment by tboerger** [comment]
Ah, and since this pr is only focused on agent to server communication, there are also somewhere documented limitations of the payload size for grpc.

**Comment by Raffo** [comment]
@tboerger I haven't commented before, but the limitation is a major problem for us as well. I'm currently just following the PR and related topics, but I'd recommend not to assume that it's not a real problem because people are not complaining. Obviously just my two cents 😄

**Comment by tcely** [comment]
@Raffo you are welcome to share my solution if you would like.

https://hub.docker.com/r/tcely/drone-agent/

**Comment by tcely** [comment]
@tboerger is this the limit you're looking for?

https://github.com/drone/drone/blob/c48150767c2700d35dcc29b110a81c8b5969175e/cmd/drone-agent/agent.go#L145

**Comment by bradrydzewski** [comment]
increased to 5mb in separate patch

**Pull request closed without merging**
