### PR TITLE
Env variable doc update

### PR DESCRIPTION
**Pull request by desktophero**
I opened this issue earlier (https://github.com/drone/drone/issues/1462) ... after a couple of hours of WTF moments trying to discern my `pull_request` build option and then getting some (greatly appreciated) direction on the "why" the behavior is happening, it seemed like a good idea to submit some doc update to help others not encounter this and/or explain in docs why they are seeing something as designed. 

I hope this is helpful :smile:

### CODE REVIEW

**Comment by desktophero** [comment]
@jackspirou ... from my issue earlier. Pulling you in for review as well

**Comment by bradrydzewski** [comment]
to avoid duplicate details, perhaps we link from the environment section to secrets page? http://readme.drone.io/usage/secrets/#pull-requests:0d943d142dc6bcdd2e544b095a49f72b

environment variables are technically different than secrets, but if that is the default place that people are looking it would be great to link between the two

**Comment by gtaylor** [comment]
Are these docs even used anymore? I thought they were pretty much all over here https://github.com/drone/docs except for the swagger.yml?

**Comment by bradrydzewski** [comment]
@gtaylor good point, I clicked the link from gmail and didn't notice which repo we were in. There is one important piece of information that hasn't been ported over yet (using the cli to register remote worker nodes) but otherwise we can delete the docs section from this repo

@desktophero we've actually move the docs to https://github.com/drone/docs ... sorry for the confusion!

**Comment by desktophero** [comment]
I can move/rewrite/enhance based on the feedback ... outside of that, cool with the content of PR?

**Comment by gtaylor** [comment]
> There is one important piece of information that hasn't been ported over yet (using the cli to register remote worker nodes)

I wonder if we should even bother, given the push-to-pull conversion? I'm assuming there won't be a need to explicitly register the workers on the CLI after that?

**Comment by desktophero** [comment]
Closing this ... I'll submit a new one based on the comments and feedback (and in the right repo). Thanks!

**Pull request closed without merging**
