### PR TITLE
Add support to ppc64le architecture

### PR DESCRIPTION
**Pull request by carlosedp**
This PR adds ppc64le architecture support to Drone.

I believe I got all requirements to build the images and supporting ppc64le architecture.

### CODE REVIEW

**Comment by tboerger** [comment]
We don't have access to any ppc64le environment for building or testing :(

**Comment by carlosedp** [comment]
Unicamp, a brazilian public university that is part of the OpenPOWER foundation has Minicloud where they provide resources for open source projects.

Go to http://openpower.ic.unicamp.br/minicloud/

It's even endorsed by IBM itself - https://developer.ibm.com/recipes/tutorials/how-to-get-free-access-to-power8-virtual-machines/

**Comment by tphoney** [comment]
Hi @carlosedp thanks for this PR, there has not been many endorsements for this and it adds a significant amount of work for us to support this platform. We would love to keep adding more platforms but we have to be cognizant of what we can support for paying customers. 
We have created https://github.com/drone/proposal to track changes like this. We actively push customers / and FOSS users here to look at features we are considering or are collaborating on.
This PR needs rebased to. So i am going to close this PR, and i would recommend if you are still interested, putting forward a proposal on or proposal site. 

Thank you for your patience.

**Comment by rpsene** [comment]
@tphoney @carlosedp hey, let's get ppc64le moving forward...  I can start working on the proposal (if not yet available), and we could do a sync up if need be.

**Pull request closed without merging**
