### PR TITLE
initial support yaml transform extensions

### PR DESCRIPTION
**Pull request by bradrydzewski**
This pull request is an initial (unstable) implementation of plugin yaml transforms. See https://github.com/drone/drone/issues/1863 for more details

### CODE REVIEW

**Comment by appleboy** [comment]
Good feature.

**Comment by bradrydzewski** [comment]
@appleboy thanks :)  hopefully we can get some feedback on how to improve, and then finalize and document the feature. In the meantime, I think we can merge this basic prototype as long as everyone knows it probably will slightly change based on feedback.

**Comment by appleboy** [comment]
Could drone support multiple yaml transform extensions? If so, I can make new PR.

**Comment by bradrydzewski** [comment]
Sure, feel free to send a pr that changes URL to a []string so it can make multiple calls

**Comment by appleboy** [comment]
@bradrydzewski Thanks.

**Pull request merged**
