### PR TITLE
Add missing space between "your" and "system administrator"

### PR DESCRIPTION
**Pull request by strk**
Otherwise the error on wrong login is very confusing...

### CODE REVIEW

**Comment by tboerger** [comment]
The ui will be replaced soon, so I don't think changes make any sense

**Comment by bradrydzewski** [comment]
as @tboerger mentioned we are soon replacing the UI w/ code my fork at [bradrydzewski/drone](https://github.com/bradrydzewski/drone) which no longer uses amber templates. Thanks though!

**Comment by strk** [comment]
@bradrydzewski should I build from your fork then ? will you accept PR there ?
(I'm also interested in running drone from a /subpath/

**Comment by tboerger** [comment]
> @bradrydzewski should I build from your fork then ? will you accept PR there ?
> (I'm also interested in running drone from a /subpath/

The subpath is a bigger efford that needs to be tested. I already started this stuff in the past but it have not been integrated yet.

**Pull request closed without merging**
