### PR TITLE
Mesos marathon

### PR DESCRIPTION
**Pull request by Dwaynekj**
Added a deploy plugin for marathon

### CODE REVIEW

**Comment by bradrydzewski** [comment]
awesome, thanks!  I know I mentioned this in gitter, but just a reminder that this won't be included in the 0.4 release (as plugins are no longer bundled with Drone) so we'll need to port to the new plugin model :)

**Comment by Dwaynekj** [comment]
@bradrydzewski Thx! I started it here https://github.com/Dwaynekj/drone-marathon. The logic may be a bit more involved

**Comment by bradrydzewski** [comment]
very cool. I put together some docs, let me know if they help at all:
http://readme.drone.io/docs/plugin/#/example.md

note that your plugin parameters will be sent in the `vargs` section of the json payload. Happy to answer any questions in the gitter room as you make progress!

**Comment by dellintosh** [comment]
Is this available?  I can't find it on the plugins listing and we recently set up a Mesos/Marathon cluster that I'd love to automate deployments to...

**Comment by gtaylor** [comment]
This might be what you are looking for: https://github.com/drone-plugins/drone-marathon

**Comment by tboerger** [comment]
> This might be what you are looking for: https://github.com/drone-plugins/drone-marathon

But this is for drone >= 0.5 which is not a stable release yet.

**Pull request merged**
