### PR TITLE
add drone build logs cmd

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@selfip.ru>

### CODE REVIEW

**Comment by tboerger** [comment]
Yeah, getting logs command back!

**Comment by vtolstov** [comment]
@tboerger  =)

**Comment by vtolstov** [comment]
i want also to get streamed logs while build not finished, but not understand how can i do that.... @bradrydzewski can you suggest ?

**Comment by vtolstov** [comment]
does i need to change something or pr ok?

**Comment by bradrydzewski** [comment]
sorry for delay, just a minor change for consistency when using `last`, if you don't mind and then we are good to merge! thanks!

**Comment by vtolstov** [comment]
@bradrydzewski sorry, what you mean with " just a minor change for consistency when using last" ?

**Comment by bradrydzewski** [comment]
nevermind, ignore that comment, it doesn't really apply here :)

**Pull request merged**
