### PR TITLE
choose ambassador by platform

### PR DESCRIPTION
**Pull request by bradrydzewski**

### CODE REVIEW

**Comment by tboerger** [comment]
Not being configurable? Especially for setups without hub access or with special requirements within companies

**Comment by bradrydzewski** [comment]
> Not being configurable? Especially for setups without hub access or with special requirements within companies

@tboerger both 0.4 and 0.5 have hardcoded ambassador images. This pull request therefore does not attempt to solve the problem where people want to change the default ambassador image, since it would be a more complex change. This PR instead attempts to provide an arm-compatible ambassador.

**Comment by tboerger** [comment]
Do I miss something or should it just be a single option within the agent that just resolves the default image for the architecture it's compiled for?

**Comment by bradrydzewski** [comment]
@tboerger it would be 3 options. Image name, entrypoint (string slice) and command (string slice) since different images / operating systems might require different commands. This is not something I'm looking to solve in this PR. It could always be a separate follow-up PR

**Comment by tboerger** [comment]
:+1:

**Comment by bradrydzewski** [comment]
I'm actually hoping docker will implement pod networking so we can use `docker network create` along with the existing `docker volume create`, and we can ditch pod networking all together. I'm not sure how likely they are to implement such a feature, but one can dream :)

**Comment by vaijab** [comment]
LGTM

**Comment by tboerger** [comment]
After merging this I can create a followup to provide those options for the agent.

**Comment by alkar** [comment]
LGTM, thanks @bradrydzewski

**Comment by bradrydzewski** [comment]
> After merging this I can create a followup to provide those options for the agent.

@tboerger after discussing with the docker folks there may be a way to remove the ambassador container completely. Let's discuss this further in gitter before we expose any more of the ambassador behavior.

**Pull request merged**
